### ISSUE TITLE
Can I make a translated versions?

### ISSUE THREAD

**Issue by 7sDream** [simoncozens/fonts-and-layout#12]
Hello Simon,

Thank you immensely for crafting such comprehensive documents on OpenType, script shaping, and text layout. Your book has been an invaluable asset in my exploration of this field.

Given the limited resources on this subject, especially in my native language, I am curious if I could have your permission to translate this online book into Chinese? I will keep it open source and allow for community edits.

Additionally, do you have any upcoming plans to complete the unfinished sections? I am particularly interested in the parts about rasterization and hinting, and I am truly looking forward to your insights on these topics.

**Comment by simoncozens** [comment]
Hi there! Yes, please translate into Chinese; I would love to see that. I hope to write some more next year.

**Comment by Jocs** [comment]
@7sDream Is there any new progress?

**Comment by 7sDream** [comment]
@Jocs 

During my leisure time in January, I completed translation of first three chapters. I have to pause after LNY because of other works and daily matters. But I will continue the translation at next week.

The current translation remains unedited and somewhat rough, so it hasn’t been publicly shared yet. I intend to release it in April if I find the time.

**Comment by 7sDream** [comment]
Since the Chinese version is basically completed, I think this issue can be closed. If @simoncozens has any typographic suggestions, we can open an issue in the Chinese version's repository for discussion.
