### ISSUE TITLE
Typo in A Brief History of Type

### ISSUE THREAD

**Issue by sergiolmartins** [simoncozens/fonts-and-layout#5]
Was reading through the initial chapters and I found a typo. Unsure if you'd like this stuff to be tracked here; If not, let me know.

The second Bézier Curve paragraph has the following sentence:
> Bézier’s contribution - as well as popularising the de Casteljau algorithm - was to made it suitable (…)

It should read:
> Bézier’s contribution - as well as popularising the de Casteljau algorithm - was to make it suitable (…)

**Comment by alerque** [comment]
I'm sure fixes like this would be appreciated. Fixing them however is probably even less typing than reporting them. For example this one you could suggest a fix via opening a PR as easily as clicking the edit (pencil) button at the top of this page: https://github.com/simoncozens/fonts-and-layout/blob/master/history.md
